server:
  port: 8081

selmag:
  services:
    catalogue:
      uri: http://localhost:8082
      registration-id: keycloak

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: HfaGmwjr5LGdZUEcD9Es0ya3lEjhlj4x
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt